---
- name: install docker dependencies
  apt:
    name: "{{ docker_deps }}"
    state: present
    cache_valid_time: 14400
    update_cache: yes
- name: install docker apt keygen
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: add docker apt repo
  apt_repository:
    state: present
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    filename: docker
- name: install docker
  apt:
    name: "{{ docker_packages }}"
    state: present
    cache_valid_time: 14400
    update_cache: yes
- name: install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
